### ISSUE TITLE
Python 3.8 throws error in the CLI when using ibridges setup

### ISSUE THREAD

**Issue by chStaiger** [iBridges-for-iRODS/iBridges#292]
```
$ ibridges setup uu-its
Traceback (most recent call last):
  File "/home/user/.local/bin/ibridges", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.10/site-packages/ibridges/__main__.py", line 116, in main
    ibridges_setup()
  File "/home/user/.local/lib/python3.10/site-packages/ibridges/__main__.py", line 276, in ibridges_setup
    env_providers = get_environment_providers()
  File "/home/user/.local/lib/python3.10/site-packages/ibridges/util.py", line 99, in get_environment_providers
    return [entry.load() for entry in entry_points(group="ibridges_server_template")]
TypeError: entry_points() got an unexpected keyword argument 'group'
$ python --version
Python 3.8.10
```

**Comment by qubixes** [comment]
@chStaiger I think I need to have a little bit more detail. Which version of importlib_metadata have you installed?

**Comment by chStaiger** [comment]
I have `importlib-metadata==1.5.0`
Upgrading to `importlib_metadata==8.5.0` solved the issue.
